{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# COVID-19 DETECTION MODELS TESTING REPORT"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/opt/anaconda3/lib/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.\n",
      "  import pandas.util.testing as tm\n"
     ]
    }
   ],
   "source": [
    "from os import listdir\n",
    "from PIL import Image\n",
    "from numpy import asarray\n",
    "from matplotlib import pyplot\n",
    "from os.path import isdir\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.metrics import confusion_matrix\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.model_selection import train_test_split"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import time\n",
    "import numpy as np\n",
    "import os\n",
    "os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # or any {'0', '1', '2'}\n",
    "\n",
    "\n",
    "import tensorflow as tf\n",
    "from tensorflow.python.ops import summary_ops_v2\n",
    "from tensorflow import keras\n",
    "from tensorflow.keras import datasets, layers, models, optimizers, metrics"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Load Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def extract_images(filename, required_size=(200, 200)):\n",
    "    # load image from file\n",
    "    image = Image.open(filename)\n",
    "    # convert to RGB, if needed\n",
    "    image = image.convert('RGB')\n",
    "    # convert to array\n",
    "    image = image.resize(required_size)\n",
    "    pixels = asarray(image, dtype=np.float32)\n",
    "    return pixels"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_images(directory):\n",
    "    images = list()\n",
    "    # enumerate files\n",
    "    for filename in listdir(directory):\n",
    "        # path\n",
    "        path = directory + filename\n",
    "        # get face\n",
    "        img = extract_images(path)\n",
    "        # store\n",
    "        images.append(img)\n",
    "    return images"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# COVID-19 VS PNEUMONIA VS NORMAL"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_dataset(directory):\n",
    "    X, y = list(), list()\n",
    "    # enumerate folders, on per class\n",
    "    for subdir in listdir(directory):\n",
    "        # path\n",
    "        path = directory + subdir + '/'\n",
    "        # skip any files that might be in the dir\n",
    "        if not isdir(path):\n",
    "            continue\n",
    "        # load all faces in the subdirectory\n",
    "        faces = load_images(path)\n",
    "        # create labels\n",
    "        labels = [subdir for _ in range(len(faces))]\n",
    "        # summarize progress\n",
    "        print('>loaded %d examples for class: %s' % (len(faces), subdir))\n",
    "        # store\n",
    "        X.extend(faces)\n",
    "        y.extend(labels)\n",
    "    return asarray(X), asarray(y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ">loaded 100 examples for class: PNEUMONIA\n",
      ">loaded 100 examples for class: NORMAL\n",
      ">loaded 94 examples for class: Covid\n"
     ]
    }
   ],
   "source": [
    "trainX, trainy = load_dataset('xray_dataset_covid19/')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "le = LabelEncoder()\n",
    "trainy = le.fit_transform(trainy)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "trainX, testX, trainy, testy = train_test_split(trainX, trainy, test_size=0.5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "compute_loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)\n",
    "compute_accuracy = tf.keras.metrics.SparseCategoricalAccuracy()\n",
    "def test_cnn_covid_pneumonia_normal(model, dataset):\n",
    "    \"\"\"\n",
    "    Perform an evaluation of `model` on the examples from `dataset`.\n",
    "    \"\"\"\n",
    "    avg_loss = metrics.Mean('loss', dtype=tf.float32)\n",
    "\n",
    "    for (images, labels) in dataset:\n",
    "        logits = model(images, training=False)\n",
    "        avg_loss(compute_loss(labels, logits))\n",
    "        compute_accuracy(labels, logits)\n",
    "\n",
    "    print('Model test set loss: {:0.4f} accuracy: {:0.2f}%'.format(\n",
    "        avg_loss.result(), compute_accuracy.result() * 100))\n",
    "\n",
    "    return(float(compute_accuracy.result() * 100))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "collapsed": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x1476ba110> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x1476c9b10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x10b10d810> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x10b111cd0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x10b114a10> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x10b118f50>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x10b11bc50> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x10b1231d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x10b123ed0> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x10b12b410>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x10b12c150> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x10b132650>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x10b135990> and <tensorflow.python.keras.layers.core.Dense object at 0x10b138a50>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x10b138a50> and <tensorflow.python.keras.layers.core.Dense object at 0x10b13cb10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x10b13cb10> and <tensorflow.python.keras.layers.core.Dense object at 0x10b13fb90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x10b13fb90> and <tensorflow.python.keras.layers.core.Dropout object at 0x10b145910>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x1476ba110> and <tensorflow.python.keras.layers.core.Reshape object at 0x1476a3410>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x10b10d810> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x1476c9b10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x10b114a10> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x10b111cd0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x10b11bc50> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x10b118f50>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x10b123ed0> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x10b1231d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x10b12c150> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x10b12b410>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Flatten object at 0x10b132fd0> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x10b132650>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x10b135990> and <tensorflow.python.keras.layers.core.Flatten object at 0x10b132fd0>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x11aba1290> and <tensorflow.python.keras.layers.core.Dropout object at 0x10b145910>).\n",
      "WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.\n"
     ]
    }
   ],
   "source": [
    "cnn_covid_pneumonia_normal = keras.models.load_model('models/CNN_Model_Covid_Pneumonia_Normal')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {
    "collapsed": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145dd4490> and <tensorflow.python.keras.layers.core.Activation object at 0x145da3950>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145da42d0> and <tensorflow.python.keras.layers.core.Dropout object at 0x145dbe790>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145dc2310> and <tensorflow.python.keras.layers.core.Activation object at 0x145dc96d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145dc9fd0> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x145dcb690>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145dd1510> and <tensorflow.python.keras.layers.core.Activation object at 0x145da9a50>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145dab2d0> and <tensorflow.python.keras.layers.core.Dropout object at 0x145db1790>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145ddd450> and <tensorflow.python.keras.layers.core.Activation object at 0x145de28d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145de5250> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x145dea910>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145dec790> and <tensorflow.python.keras.layers.core.Activation object at 0x145defc10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145df4550> and <tensorflow.python.keras.layers.core.Dropout object at 0x145df8a10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145df9690> and <tensorflow.python.keras.layers.core.Activation object at 0x145e00b10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145e04490> and <tensorflow.python.keras.layers.core.Dropout object at 0x145e0a950>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145e0d610> and <tensorflow.python.keras.layers.core.Activation object at 0x145e11a90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145e15410> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x145e1aad0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145e1e950> and <tensorflow.python.keras.layers.core.Activation object at 0x145e21dd0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145e26750> and <tensorflow.python.keras.layers.core.Dropout object at 0x145e35c10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145e388d0> and <tensorflow.python.keras.layers.core.Activation object at 0x145e3bd90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145e3f710> and <tensorflow.python.keras.layers.core.Dropout object at 0x145e44bd0>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145e4a890> and <tensorflow.python.keras.layers.core.Activation object at 0x145e4cd50>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145e516d0> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x145e57d90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145e5bc10> and <tensorflow.python.keras.layers.core.Activation object at 0x145e600d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145e60a10> and <tensorflow.python.keras.layers.core.Dropout object at 0x145e66ed0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145e6cb90> and <tensorflow.python.keras.layers.core.Activation object at 0x145fe2090>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145fe29d0> and <tensorflow.python.keras.layers.core.Dropout object at 0x145fe7e90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145feeb50> and <tensorflow.python.keras.layers.core.Activation object at 0x145ff1fd0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145ff2990> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x145ff9fd0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x146000b50> and <tensorflow.python.keras.layers.core.Activation object at 0x146005a90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x146009410> and <tensorflow.python.keras.layers.core.Dropout object at 0x14600f810>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145da42d0> and <tensorflow.python.keras.layers.core.Activation object at 0x145da3950>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145dc2310> and <tensorflow.python.keras.layers.core.Dropout object at 0x145dbe790>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145dc9fd0> and <tensorflow.python.keras.layers.core.Activation object at 0x145dc96d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145dd1510> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x145dcb690>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145dab2d0> and <tensorflow.python.keras.layers.core.Activation object at 0x145da9a50>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145ddd450> and <tensorflow.python.keras.layers.core.Dropout object at 0x145db1790>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145de5250> and <tensorflow.python.keras.layers.core.Activation object at 0x145de28d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145dec790> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x145dea910>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145df4550> and <tensorflow.python.keras.layers.core.Activation object at 0x145defc10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145df9690> and <tensorflow.python.keras.layers.core.Dropout object at 0x145df8a10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145e04490> and <tensorflow.python.keras.layers.core.Activation object at 0x145e00b10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145e0d610> and <tensorflow.python.keras.layers.core.Dropout object at 0x145e0a950>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145e15410> and <tensorflow.python.keras.layers.core.Activation object at 0x145e11a90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145e1e950> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x145e1aad0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145e26750> and <tensorflow.python.keras.layers.core.Activation object at 0x145e21dd0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145e388d0> and <tensorflow.python.keras.layers.core.Dropout object at 0x145e35c10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145e3f710> and <tensorflow.python.keras.layers.core.Activation object at 0x145e3bd90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145e4a890> and <tensorflow.python.keras.layers.core.Dropout object at 0x145e44bd0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145e516d0> and <tensorflow.python.keras.layers.core.Activation object at 0x145e4cd50>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145e5bc10> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x145e57d90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145e60a10> and <tensorflow.python.keras.layers.core.Activation object at 0x145e600d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145e6cb90> and <tensorflow.python.keras.layers.core.Dropout object at 0x145e66ed0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145fe29d0> and <tensorflow.python.keras.layers.core.Activation object at 0x145fe2090>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x145feeb50> and <tensorflow.python.keras.layers.core.Dropout object at 0x145fe7e90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x145ff2990> and <tensorflow.python.keras.layers.core.Activation object at 0x145ff1fd0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dropout object at 0x145ffa910> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x145ff9fd0>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Flatten object at 0x1460000d0> and <tensorflow.python.keras.layers.core.Dropout object at 0x145ffa910>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x146000b50> and <tensorflow.python.keras.layers.core.Flatten object at 0x1460000d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x146009410> and <tensorflow.python.keras.layers.core.Activation object at 0x146005a90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x146013250> and <tensorflow.python.keras.layers.core.Dropout object at 0x14600f810>).\n",
      "WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.\n"
     ]
    }
   ],
   "source": [
    "vgg_covid_pneumonia_normal = keras.models.load_model('models/VGG16_Model_Covid_Pneumonia_Normal')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "test_ds = tf.data.Dataset.from_tensor_slices((testX, testy)).batch(200)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model test set loss: 1.0288 accuracy: 90.48%\n"
     ]
    }
   ],
   "source": [
    "cnn_acc = test_cnn_covid_pneumonia_normal(cnn_covid_pneumonia_normal,test_ds)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "test acc: 0.9455782\n"
     ]
    }
   ],
   "source": [
    "db_test = tf.data.Dataset.from_tensor_slices((testX, testy)).batch(256)\n",
    "metric = keras.metrics.CategoricalAccuracy()\n",
    "for x, y in db_test:\n",
    "    # [b, 1] => [b]\n",
    "    # y = tf.squeeze(y, axis=1)\n",
    "    # [b, 10]\n",
    "    y = tf.one_hot(y, depth=3)\n",
    "\n",
    "    logits = vgg_covid_pneumonia_normal.predict(x)\n",
    "    # be careful, these functions can accept y as [b] without warnning.\n",
    "    metric.update_state(y, logits)\n",
    "    cm_cpn = confusion_matrix(tf.math.argmax(y, axis=1), tf.math.argmax(logits, axis=1))\n",
    "print('test acc:', metric.result().numpy())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "covid_pneumonia_normal_models = ['cnn_covid_pneumonia_normal', 'resnet_covid_pneumonia_normal', 'vgg_covid_pneumonia_normal']\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "covid_pneumonia_normal_acc = [cnn_acc, None, metric.result().numpy()*100]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAggAAAD4CAYAAACJ8R5TAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjEsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8QZhcZAAAZT0lEQVR4nO3deZRmVX3u8e8DjSJgAEEJitqoIKIISoMDiIAsc801xhm9DkCuyc0VFYxjzAQmJqhxBiSGRIjLqwiCIholQQFtmbpppBkaSRpUCAooDqBppt/94+xavF27uqoa6HqB+n7WqlXn7PecfX771KHf593nVJGqQpIkadR64y5AkiTd9xgQJElSx4AgSZI6BgRJktQxIEiSpM6CcRcg3Vu23HLLWrhw4bjLkKT7laVLl95YVQ+f3G5A0APGwoULWbJkybjLkKT7lSQ/mKrdWwySJKljQJAkSR0DgiRJ6hgQJElSx4AgSZI6BgRJktTx1xz1gHH5NT9l13f8y7jLkKS7ZekHXz/uElbjDIIkSeoYECRJUseAIEmSOgYESZLUMSBIkqSOAUGSJHUMCJIkqWNAkCRJHQOCJEnqGBAkSVLHgCBJkjoGBEmS1DEgSJKkjgFBkiR1DAiSJKljQJAkSR0DgiRJ6hgQJElSx4AgSZI6BgRJktQxIEiSpI4BQZIkdQwIkiSpY0CQJEkdA4IkSerMy4CQ5EVJ3r2G126e63rmSpLvjruGuyPJmUkWjbsOSZpPFoy7gHGoqlOBU8ddx1yrqmfP9TGTLKiq2+f6uJKke2adzSAkeX2Si5N8L8lnkhyX5ONJvptkZZKXt+32bp8QT0qyIslnk2SafndrfXwvyflJHppkwySfTrI8ybIk+7Rtz0vy5JF9z0yya5IDkxzZ2rZNck6SC5L89Qxj2jvJ2UlOSXJZkmOSrNdeuznJ+1pd5ybZqrU/PMkXW/8XJNmjtR+W5O0jfV+SZGH7WpHk2Nb22ST7JVmc5Moku7ftH5bkS+0cn5vkqSP9/nMb68okbxk5xs3t+yZJzkhyYTtnvz/NmBcmuTzJPya5NMnpSR7SXtulHfvidk42HznPf5vkLOCQ9rP/ZJJvtZqe22q8PMlxI8f6ZJIl7TiHT/ezkCStW+skILQ35T8D9q2qnYFD2ktbA3sCLwSOGNnlacChwI7A44A91tDvg4ATgENav/sBvwEOBqiqnYBXA8cn2RD4PPDKtu/WwCOraumkbj8GfLKqdgN+PIvh7Q68DdgJeDzw0ta+MXBuq+ts4A9H+v9I6/9lwLGzOMYT2n5PBXYA/hfDeXs78J62zeHAsqp6amv7l5H9dwB+p9X6V0k2mNT/fwMvqaqnA/sAH5oulAHbAUdV1ZOBn7dx0I75rlbDcuCvRvbZrKqeW1UfauubA/sCbwW+AnwEeDKwU5Jd2jZ/VlWL2rifOxF6ppPkj1qoWHL7r3810+aSpFlaVzMI+wInVdWNAFX1s9b+paq6s6ouA7Ya2f78qrqmqu4ELgIWrqHfJwLXVdUFrd9ftunrPYHPtLYVwA+A7YEvAK9o+74SOHGKPvcAPteWPzOLsZ1fVSur6o62356t/VbgtLa8dGQM+wFHJrmI4bbGbyV56AzHuKqqlrfzcSlwRlUVw5vwRL+jY/4msEWSTdtrX62qVe38X8/q5xogwN8muRj4d+BRU2wzuZ6LRsfWjrVZVZ3V2o8H9hrZ54RJfXxlZAw/mTS+iTG9MsmFwDKG8LDjNDXRxv6pqlpUVYsWbDTTaZUkzda6egYhQE3RvmrSNlO138Ga61pTv1N++q2qa5P8tH0S3R/4P2vod6o+12TythPrt7U3QFh9DOsBz6qq36xWcHI7qwe0DUeWR8/HnSPrd470O9WYJ44/0/l8DfBwYNequi3J1ZOOP9nk/h4yzbYTbllDH6PjmVhfkGRbhhmS3arqpnbrYbqaJEnr0LqaQTiD4dPgFjDcL7+X+l0BPDLJbq3fhyZZwDCl/5rWtj3wGOCKts/ngXcCm1bV8in6XAy8qi2/ZhY17N6eW1iPIXR8Z4btTwfeNLEyMp1+NfD01vZ0YNtZHHvU6Jj3Bm6sql/Oct9NgetbONgHeOxaHpuq+gVwU5LntKbXAWdNs8tMfoshVPyiPb/xgnvQlyTpHlonMwhVdWmS9wFnJbmDYcr43uj31iT7A59oD8r9hmEK/2jgmCTLgduBA6tq4lPqSQz389f0AOIhwP9LcgjwxVmUcQ7D8xM7MbxJnzLD9m8BjmrT+RNh5o/bsV7fbj1cAHx/FscedRjw6dbvr4ED1mLfzwJfSbKE4ZbOirU89oQDGM77RsBK4KC72Q9V9b0kyxhuOaxkCG6SpDHJXbPimkn7pP72qnrhuGtRb+Pf3rZ2eJ2//CDp/mnpB18/luMmWdoeEF/NvPxDSZIkaXr32T+UlOQU+vvy76qqb8zBsXei/42GVVX1DODMdX38cWjPi5wxxUvPq6qfznU9kqTxus8GhKp6yRiPvRzYZcYNH0BaCJhXY5YkrZm3GCRJUseAIEmSOgYESZLUMSBIkqSOAUGSJHUMCJIkqWNAkCRJHQOCJEnqGBAkSVLHgCBJkjoGBEmS1DEgSJKkjgFBkiR1DAiSJKljQJAkSR0DgiRJ6hgQJElSx4AgSZI6BgRJktQxIEiSpM6CcRcg3VuetM0WLPng68ddhiQ9IDiDIEmSOgYESZLUMSBIkqSOAUGSJHUMCJIkqWNAkCRJHQOCJEnqGBAkSVLHgCBJkjoGBEmS1DEgSJKkjgFBkiR1DAiSJKljQJAkSR0DgiRJ6hgQJElSx4AgSZI6BgRJktQxIEiSpI4BQZIkdQwIkiSpY0CQJEkdA4IkSeoYECRJUseAIEmSOgYESZLUMSBIkqSOAUGSJHUMCJIkqWNAkCRJHQOCJEnqGBAkSVLHgCBJkjoGBEmS1DEgSJKkjgFBkiR1DAiSJKljQJAkSR0DgiRJ6hgQJElS5z4VEJJsluSNc3SsY5PsOEX7gUmOnIsa5lqSFyV597jrWFtJFia5ZNx1SNJ8slYBIYN1GSo2A+YkIFTVG6rqsrk41n1FVZ1aVUfM5THn4JqRJK0DM/7D3T69XZ7kaOBC4HVJzklyYZITk2zStjsiyWVJLk7y963tuCQfT/LdJCuTvHyk33ckuaBtf3hrPgJ4fJKLknxwmpremWR5ku8lOaK17ZLk3NbfKUk2T/KkJOdPGsvFbfnMJIva8kFJvp/kLGCPGc7HcUmOSfLtts8LW/uBSU5O8vUkVyb5wMg+z1/DObs6yZZteVGSM9vyYUmOT3J62+alST7Qxvz1JBu07Z6XZFlr/+ckDx7p9/B2vOVJdhip8ci2/HtJzmv7/3uSraYZ82Gt/zPbz/EtI6/9SZJL2tehI+d59Jp5dJKbk7w/ydJ2vN1H+nvRyH7fbnVfmOTZ0/0s2j5/lGRJkiU33HDDTJtLkmarqqb9AhYCdwLPBLYEzgY2bq+9C/hL4GHAFUBa+2bt+3HAiQxBZEfgP1r784FPAWmvnQbs1Y51yQz1vAD4LrBRW39Y+34x8Ny2/F7go235IuBxI/X+eVs+E1gEbA38EHg48CBgMXDkNMc/Dvh6q3s74BpgQ+BAYCWwaVv/AfDoNZ2ztnw1sGVbXgSc2ZYPA74DbADsDPwaeEF77RTgxe0YPwK2b+3/Ahw60u+b2/IbgWPb8oETYwM2H/l5vQH40DRjPqyd8we38fy01bYrsBzYGNgEuBR4GiPXzEgfNWkMp4+M76LWvhGwYVveDlgycg1Oe11UFbvuumtJktbOxL+1k78WMDs/qKpz26flHYHFSWB4Qz0H+CXw38CxSb7K8IY/4UtVdSdw2cin1Oe3r2VtfZP2hvDDWdSyH/Dpqvo1QFX9LMmmDKHkrLbN8QzBBOALwCsZZif2b1+jnsHwxnwDQJITgO1nqOELbUxXJlkJ7NDaz6iqX7R+LgMey3DbZKpzNpN/rarbkiwH1mcIJTC8IS8EnghcVVXfHxnzwcBH2/rJ7ftS4KVT9L8NcEKSrVtNV81Qz1erahWwKsn1wFbAnsApVXVLG/PJwHOAU2nXzMj+t04aw6qR8S1s7RsARybZBbiDmX8OkqR1ZLYB4Zb2PcC/VdWrJ2+QZHfgecCrgDcB+7aXVo1uNvL976rqHyb1sXAWtYTh0+hsnQCc2N68qqqunGKbtelvqu0n1kfHegfD+V3jOQNu567bPBtOem0VQFXdmeS2lvJg+GQ+0e90JmqZqGOyTwAfrqpTk+zNMEswm/5G+5yuhlsmrU8ew+j4Jup7K/AThlmF9RhCpyRpDNb24bFzgT2SPAEgyUZJtm/31Detqq8BhwK7zNDPN4A/GLkX/6gkjwB+BTx0hn1Pb/tu1PZ9WPvUflOS57RtXgecBVBV/8nwhvYXDGFhsvOAvZNs0e7tv2KG4wO8Isl6SR4PPI7h9sqaTHnO2mtXM0zTA7xsFscdtQJYONEvI2OepU2Ba9vyAWt57AlnAy9uY9oYeAnw7bvZ10RN17XZmdcxzJxIksZgtjMIAFTVDUkOBD438UAc8OcMb+xfTrIhw6fKt87Qz+lJngSc06bdbwZeW1X/mWRxhl9p+9eqescU+369TUEvSXIr8DXgPQxvcse04LASOGhktxOADwLbTtHfdUkOY5j2v47hobqZ3piuYHgz3gr446r67zaOqca6pnP2feBw4J+SvIchqMxaO+ZBDLMjC4ALgGPWoovD2r7XMoSY7tzMooYLkxwHTDwIemxVLZvlTNBUjga+mOQVwLfoZyEkSXMkd836ajbaG+JpVXXSuGvR6hYtWlRLliwZdxmSdL+SZGlVLZrc7u+nS5KkzlrdYphLSXYCPjOpeVVVPWOOjv9n9M8jnFhVB87F8ceh3bI4ZFLz4qo6eBz1SJLGx1sMesDwFoMkrT1vMUiSpFkzIEiSpI4BQZIkdQwIkiSpY0CQJEkdA4IkSeoYECRJUseAIEmSOgYESZLUMSBIkqSOAUGSJHUMCJIkqWNAkCRJHQOCJEnqGBAkSVLHgCBJkjoGBEmS1DEgSJKkjgFBkiR1DAiSJKljQJAkSR0DgiRJ6hgQJElSx4AgSZI6BgRJktQxIEiSpI4BQZIkdQwIkiSpY0CQJEkdA4IkSeoYECRJUseAIEmSOgYESZLUMSBIkqTOgnEXIN1bVly/gj0+sce4y5CkObX4zYvXSb/OIEiSpI4BQZIkdQwIkiSpY0CQJEkdA4IkSeoYECRJUseAIEmSOgYESZLUMSBIkqSOAUGSJHUMCJIkqWNAkCRJHQOCJEnqGBAkSVLHgCBJkjoGBEmS1DEgSJKkjgFBkiR1DAiSJKljQJAkSR0DgiRJ6hgQJElSx4AgSZI6BgRJktQxIEiSpM68DQhJvruG9uOSvHyu65kLSd6bZL9x17G2khyY5Mhx1yFJ88mCcRcwLlX17HHXMNeq6i/n+phJFlTV7XN9XEnSPbNOZhCSvD/JG0fWD0vytiRHJ7k0yWlJvjbxST3J7yZZkeQ7ST6e5LRp+t4kyaeTLE9ycZKXtfZXt7ZLkry/tf3fJB8Y2ffAJJ9oyze370lyZJLLknwVeMQMY7u6je/89vWE1n5cq/27SVaOzkIkeUeSC1q9h7e2hUkuGdnm7UkOa8tnJvlIkrOTXJ5ktyQnJ7kyyd+M7PMnbbyXJDl0pN/Lk/xjO9enJ3nISI0T5/wvW02XJPlUkkwz5jNHxvz9JM9p7RuO/CyWJdln5DyfmOQrwOlJ9k5yVpIvtP2PSPKa1t/yJI9v+/1ekvNaX/+eZKvpfhaSpHVnXd1i+Dyw/8j6K4EbgIXATsAbgGfB8CYD/APwgqraE3j4DH3/BfCLqtqpqp4KfDPJI4H3A/sCuwC7JXkxcBLw0pF99wdOmNTfS4Antrr+EJjNzMIvq2p34EjgoyPtWwN7Ai8Ejmjjez6wHbB7q23XJHvN4hi3VtVewDHAl4GDgacABybZIsmuwEHAM4BnAn+Y5Glt3+2Ao6rqycDPgZdN0f+RVbVbVT0FeEireToL2pgPBf6qtR0MUFU7Aa8Gjm8/Txh+vgdU1b5tfWfgEIbz/Dpg+9bfscCb2zbfAZ5ZVU9juIbeOUNNJPmjJEuSLLnt5ttm2lySNEvrJCBU1TLgEUkemWRn4Cbg6cCJVXVnVf0Y+FbbfAdgZVVd1dY/N0P3+wFHjRzrJmA34MyquqFNZ38W2KuqbgBWJnlmki0YgsDiSf3tBXyuqu6oqv8CvjmLIX5u5PuzRtq/1MZ3GTDx6ff57WsZcGEb73azOMap7fty4NKquq6qVgErgUczBJFTquqWqroZOBl4Ttvnqqq6qC0vZQhmk+3TPq0vZwhWT56hnpOn6G9P4DMAVbUC+AGwfXvt36rqZyP7XzAyhv8ETh8Z30R/2wDfaDW9YxY1UVWfqqpFVbVog002mGlzSdIsrctnEE4CXg78NsOnwSesYbs1Tm1Ps32tRR8nMMxgrGB4Q528L1P0N5Naw/KqKWoK8HdV9Q+jHSTZhtUD2oasbqKvOyf1eyfDz226MY9ufwfDDMHosTcEjgYWVdWP2q2NycdfU593cNd1M10Nt0xT0+iYJsYD8Angw1V1apK9gcNmqEmStI6sy99i+DzwKoaQcBLD9PHLkqzX7i3v3bZbATwuycK2vj/TOx1408RKks2B84DnJtkyyfoM091ntU1OBl7c2ibfXgA4G3hVkvWTbA3sM4ux7T/y/ZwZtv0G8AdJNmn1PirJI4CfMMyybJHkwcw8xT9V3S9OslGSjRlulXx7lvtOhIEbW11397c2zgZeA5Bke+AxwBV3sy+ATYFr2/IB96AfSdI9tM5mEKrq0iQPBa6tquuSfBF4HnAJ8H2GN/VfVNVvMjzQ+PUkNwLnz9D13wBHtQf87gAOr6qTk/wpw22LAF+rqi+3Om5KchmwY1VN1fcpDFPsy1tdZ02xzWQPTnIeQ8B69Qzn4fQkTwLOac8B3gy8tqquT/Ledh6uYghKs1ZVFyY5jrvO17FVtWwkaE2378+T/CPDmK8GLlibY484Gjim3RK4HTiwqlZN87zjTA4DTkxyLXAusO3d7UiSdM9k6hn3dXSwZJOqurk9D3A+sEdV/XikPQzPF1xZVR+Zs8LWQpKrGabmbxx3LVrdJo/ZpHZ+x87jLkOS5tTiN09+tG7tJFlaVYsmt8/130E4LclmwIOAv24PK8LwBP4BrX0Zw281SJKkMZnTgFBVe6+h/SPAajMGSQ5i+LW4UYur6uB1U93qkpxCP8X9rqpaOBfHH4ckRwF7TGr+WFV9ehz1SJLG5z77lxTbm9LY3piq6iXjOva4zFX4kiTd983b/xeDJElaMwOCJEnqGBAkSVLHgCBJkjoGBEmS1DEgSJKkjgFBkiR1DAiSJKljQJAkSR0DgiRJ6hgQJElSx4AgSZI6BgRJktQxIEiSpI4BQZIkdQwIkiSpY0CQJEkdA4IkSeoYECRJUseAIEmSOgvGXYB0b9nhETuw+M2Lx12GJD0gOIMgSZI6BgRJktQxIEiSpI4BQZIkdQwIkiSpY0CQJEmdVNW4a5DuFUl+BVwx7jruI7YEbhx3Efchno+7eC5W5/mAx1bVwyc3+ncQ9EByRVUtGncR9wVJlngu7uL5uIvnYnWejzXzFoMkSeoYECRJUseAoAeST427gPsQz8XqPB938VyszvOxBj6kKEmSOs4gSJKkjgFBkiR1DAi630vyP5JckeQ/krx73PXMtSSPTvKtJJcnuTTJIa39YUn+LcmV7fvm4651riRZP8myJKe19W2TnNfOxQlJHjTuGudKks2SnJRkRbtGnjVfr40kb23/jVyS5HNJNpzP18ZMDAi6X0uyPnAU8AJgR+DVSXYcb1Vz7nbgbVX1JOCZwMHtHLwbOKOqtgPOaOvzxSHA5SPr7wc+0s7FTcD/HktV4/Ex4OtVtQOwM8N5mXfXRpJHAW8BFlXVU4D1gVcxv6+NaRkQdH+3O/AfVbWyqm4FPg/8/phrmlNVdV1VXdiWf8XwBvAohvNwfNvseODF46lwbiXZBvifwLFtPcC+wEltk/l0Ln4L2Av4J4CqurWqfs48vTYY/jjgQ5IsADYCrmOeXhuzYUDQ/d2jgB+NrF/T2ualJAuBpwHnAVtV1XUwhAjgEeOrbE59FHgncGdb3wL4eVXd3tbn0zXyOOAG4NPtlsuxSTZmHl4bVXUt8PfADxmCwS+Apczfa2NGBgTd32WKtnn5u7tJNgG+CBxaVb8cdz3jkOSFwPVVtXS0eYpN58s1sgB4OvDJqnoacAvz4HbCVNpzFr8PbAs8EtiY4dbkZPPl2piRAUH3d9cAjx5Z3wb4rzHVMjZJNmAIB5+tqpNb80+SbN1e3xq4flz1zaE9gBcluZrhdtO+DDMKm7VpZZhf18g1wDVVdV5bP4khMMzHa2M/4KqquqGqbgNOBp7N/L02ZmRA0P3dBcB27UnkBzE8dHTqmGuaU+0e+z8Bl1fVh0deOhU4oC0fAHx5rmuba1X1p1W1TVUtZLgWvllVrwG+Bby8bTYvzgVAVf0Y+FGSJ7am5wGXMQ+vDYZbC89MslH7b2biXMzLa2M2/EuKut9L8rsMnxLXB/65qt435pLmVJI9gW8Dy7nrvvt7GJ5D+ALwGIZ/HF9RVT8bS5FjkGRv4O1V9cIkj2OYUXgYsAx4bVWtGmd9cyXJLgwPbD4IWAkcxPDhcN5dG0kOB/Zn+M2fZcAbGJ45mJfXxkwMCJIkqeMtBkmS1DEgSJKkjgFBkiR1DAiSJKljQJAkSR0DgiRJ6hgQJElS5/8DrMYAmLEfwXMAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "sns.barplot(x=covid_pneumonia_normal_acc, y=covid_pneumonia_normal_models)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>0</th>\n",
       "      <th>1</th>\n",
       "      <th>2</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>47</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>0</td>\n",
       "      <td>49</td>\n",
       "      <td>4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>43</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    0   1   2\n",
       "0  47   1   1\n",
       "1   0  49   4\n",
       "2   0   2  43"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_cm_cpn = pd.DataFrame(cm_cpn)\n",
    "df_cm_cpn"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# COVID-19 VS PNEUMONIA VS NORMAL REPORT\n",
    "\n",
    "### CNN ACCURACY -> 90.48%\n",
    "### VGG ACCURACY -> 94.5%"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# COVID-19 VS NORMAL"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_dataset(directory):\n",
    "    X, y = list(), list()\n",
    "    # enumerate folders, on per class\n",
    "    for subdir in ['Covid', 'NORMAL']:\n",
    "        # path\n",
    "        path = directory + subdir + '/'\n",
    "        # skip any files that might be in the dir\n",
    "        if not isdir(path):\n",
    "            continue\n",
    "        # load all faces in the subdirectory\n",
    "        faces = load_images(path)\n",
    "        # create labels\n",
    "        labels = [subdir for _ in range(len(faces))]\n",
    "        # summarize progress\n",
    "        print('>loaded %d examples for class: %s' % (len(faces), subdir))\n",
    "        # store\n",
    "        X.extend(faces)\n",
    "        y.extend(labels)\n",
    "    return asarray(X), asarray(y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ">loaded 94 examples for class: Covid\n",
      ">loaded 100 examples for class: NORMAL\n"
     ]
    }
   ],
   "source": [
    "trainX, trainy = load_dataset('xray_dataset_covid19/')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "le = LabelEncoder()\n",
    "trainy = le.fit_transform(trainy)\n",
    "\n",
    "trainX, testX, trainy, testy = train_test_split(trainX, trainy, test_size=0.5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [],
   "source": [
    "compute_loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)\n",
    "compute_accuracy = tf.keras.metrics.SparseCategoricalAccuracy()\n",
    "def test_cnn_covid_pneumonia_normal(model, dataset):\n",
    "    \"\"\"\n",
    "    Perform an evaluation of `model` on the examples from `dataset`.\n",
    "    \"\"\"\n",
    "    avg_loss = metrics.Mean('loss', dtype=tf.float32)\n",
    "\n",
    "    for (images, labels) in dataset:\n",
    "        logits = model(images, training=False)\n",
    "        avg_loss(compute_loss(labels, logits))\n",
    "        compute_accuracy(labels, logits)\n",
    "\n",
    "    print('Model test set loss: {:0.4f} accuracy: {:0.2f}%'.format(\n",
    "        avg_loss.result(), compute_accuracy.result() * 100))\n",
    "\n",
    "    return(float(compute_accuracy.result() * 100))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.\n"
     ]
    }
   ],
   "source": [
    "cnn_covid_normal = keras.models.load_model('models/CNN_model_normal.h5')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [],
   "source": [
    "resnet_covid_normal = keras.models.load_model('models/ResNet_Model_Covid_Normal')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {
    "collapsed": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b4dad0> and <tensorflow.python.keras.layers.core.Activation object at 0x165b330d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b17950> and <tensorflow.python.keras.layers.core.Dropout object at 0x165b34b90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b36810> and <tensorflow.python.keras.layers.core.Activation object at 0x165b39c90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b3d610> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x165b41d50>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b46bd0> and <tensorflow.python.keras.layers.core.Activation object at 0x165b1b090>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b1b9d0> and <tensorflow.python.keras.layers.core.Dropout object at 0x165b1fe90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b23b50> and <tensorflow.python.keras.layers.core.Activation object at 0x165b27f90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b47910> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x165b53fd0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b57ed0> and <tensorflow.python.keras.layers.core.Activation object at 0x165b5e390>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b5ecd0> and <tensorflow.python.keras.layers.core.Dropout object at 0x165b661d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b66e50> and <tensorflow.python.keras.layers.core.Activation object at 0x165b6f2d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b6fc10> and <tensorflow.python.keras.layers.core.Dropout object at 0x165b75110>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b75d90> and <tensorflow.python.keras.layers.core.Activation object at 0x165b7f250>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b7fb90> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x165b86310>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b89190> and <tensorflow.python.keras.layers.core.Activation object at 0x165b8e610>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b8ef50> and <tensorflow.python.keras.layers.core.Dropout object at 0x165b98450>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b9b110> and <tensorflow.python.keras.layers.core.Activation object at 0x165b9f590>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b9fed0> and <tensorflow.python.keras.layers.core.Dropout object at 0x165ba83d0>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165baa0d0> and <tensorflow.python.keras.layers.core.Activation object at 0x165bae550>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165baee90> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x165bb8610>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165bba490> and <tensorflow.python.keras.layers.core.Activation object at 0x165bbe910>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165bc3290> and <tensorflow.python.keras.layers.core.Dropout object at 0x15a018750>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x15a01a410> and <tensorflow.python.keras.layers.core.Activation object at 0x15a01e8d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x15a023210> and <tensorflow.python.keras.layers.core.Dropout object at 0x15a0286d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x15a02b390> and <tensorflow.python.keras.layers.core.Activation object at 0x15a030850>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x15a0331d0> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x15a039910>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x15a03f410> and <tensorflow.python.keras.layers.core.Activation object at 0x15a044350>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x15a044c90> and <tensorflow.python.keras.layers.core.Dropout object at 0x15a04e0d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b17950> and <tensorflow.python.keras.layers.core.Activation object at 0x165b330d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b36810> and <tensorflow.python.keras.layers.core.Dropout object at 0x165b34b90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b3d610> and <tensorflow.python.keras.layers.core.Activation object at 0x165b39c90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b46bd0> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x165b41d50>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b1b9d0> and <tensorflow.python.keras.layers.core.Activation object at 0x165b1b090>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b23b50> and <tensorflow.python.keras.layers.core.Dropout object at 0x165b1fe90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b47910> and <tensorflow.python.keras.layers.core.Activation object at 0x165b27f90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b57ed0> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x165b53fd0>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b5ecd0> and <tensorflow.python.keras.layers.core.Activation object at 0x165b5e390>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b66e50> and <tensorflow.python.keras.layers.core.Dropout object at 0x165b661d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b6fc10> and <tensorflow.python.keras.layers.core.Activation object at 0x165b6f2d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b75d90> and <tensorflow.python.keras.layers.core.Dropout object at 0x165b75110>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b7fb90> and <tensorflow.python.keras.layers.core.Activation object at 0x165b7f250>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b89190> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x165b86310>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b8ef50> and <tensorflow.python.keras.layers.core.Activation object at 0x165b8e610>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165b9b110> and <tensorflow.python.keras.layers.core.Dropout object at 0x165b98450>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165b9fed0> and <tensorflow.python.keras.layers.core.Activation object at 0x165b9f590>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165baa0d0> and <tensorflow.python.keras.layers.core.Dropout object at 0x165ba83d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165baee90> and <tensorflow.python.keras.layers.core.Activation object at 0x165bae550>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x165bba490> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x165bb8610>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x165bc3290> and <tensorflow.python.keras.layers.core.Activation object at 0x165bbe910>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x15a01a410> and <tensorflow.python.keras.layers.core.Dropout object at 0x15a018750>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x15a023210> and <tensorflow.python.keras.layers.core.Activation object at 0x15a01e8d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x15a02b390> and <tensorflow.python.keras.layers.core.Dropout object at 0x15a0286d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x15a0331d0> and <tensorflow.python.keras.layers.core.Activation object at 0x15a030850>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dropout object at 0x15a03c1d0> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x15a039910>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Flatten object at 0x15a03c950> and <tensorflow.python.keras.layers.core.Dropout object at 0x15a03c1d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x15a03f410> and <tensorflow.python.keras.layers.core.Flatten object at 0x15a03c950>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x15a044c90> and <tensorflow.python.keras.layers.core.Activation object at 0x15a044350>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x15a04ea90> and <tensorflow.python.keras.layers.core.Dropout object at 0x15a04e0d0>).\n",
      "WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.\n"
     ]
    }
   ],
   "source": [
    "vgg_covid_normal = keras.models.load_model('models/VGG16_Model_Covid_Normal')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model test set loss: 0.6723 accuracy: 93.81%\n"
     ]
    }
   ],
   "source": [
    "test_ds = tf.data.Dataset.from_tensor_slices((testX, testy)).batch(200)\n",
    "\n",
    "cnn_acc = test_cnn_covid_pneumonia_normal(cnn_covid_normal,test_ds)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4/4 [==============================] - 13s 3s/step - loss: 0.6514 - accuracy: 0.7732\n"
     ]
    }
   ],
   "source": [
    "testy_ohe = tf.one_hot(testy, depth=3).numpy()\n",
    "res = resnet_covid_normal.evaluate(testX, testy_ohe, verbose=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "test acc: 1.0\n"
     ]
    }
   ],
   "source": [
    "db_test = tf.data.Dataset.from_tensor_slices((testX, testy)).batch(256)\n",
    "metric = keras.metrics.CategoricalAccuracy()\n",
    "for x, y in db_test:\n",
    "    # [b, 1] => [b]\n",
    "    # y = tf.squeeze(y, axis=1)\n",
    "    # [b, 10]\n",
    "    y = tf.one_hot(y, depth=3)\n",
    "\n",
    "    logits = vgg_covid_normal.predict(x)\n",
    "    # be careful, these functions can accept y as [b] without warnning.\n",
    "    metric.update_state(y, logits)\n",
    "    cm_cn = confusion_matrix(tf.math.argmax(y, axis=1), tf.math.argmax(logits, axis=1))\n",
    "print('test acc:', metric.result().numpy())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAcsAAAD4CAYAAACDm83wAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjEsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8QZhcZAAAUIUlEQVR4nO3de5RmVX3m8e+TbggiDAioAZRpCAgiCEqDGBjSQVZWdBiFBGiQcEuUrMQgJhPRmJFIDDM6ZHTiNWEZLrIcbi0oYxwvS25Jy63bDjSXVgyIwTQKgSAXBaF/88e7e1kWVb2rL2+9bdX3s1aves+uc/b57fdU19N7n1PVqSokSdLkfmHUBUiStLEzLCVJ6jAsJUnqMCwlSeowLCVJ6pg76gI0HNttt13Nmzdv1GVI0s+VpUuXPlRVLxzfbljOUPPmzWPJkiWjLkOSfq4kuW+idpdhJUnqMCwlSeowLCVJ6jAsJUnqMCwlSeowLCVJ6vBHR2aou+7/N/Z756dHXYYkrdHSc04cdQlT4sxSkqQOw1KSpA7DUpKkDsNSkqQOw1KSpA7DUpKkDsNSkqQOw1KSpA7DUpKkDsNSkqQOw1KSpA7DUpKkDsNSkqQOw1KSpA7DUpKkDsNSkqQOw1KSpA7DUpKkDsNSkqQOw1KSpA7DUpKkDsNSkqQOw1KSpA7DUpKkDsNSkqSOWRmWSd6Y5N2TfO7x6a5nbST5TpLtRl2HJM0mc0ddwChU1VXAVdN93iRzqurZ6T6vJGn9DG1mmeTEJLcluTXJRUkuSPKRJF9Pck+So9p+C5Jcm2RRkhVJPpMka+h3/9bHrUluTrJlks2SnJ9keZJlSX6t7XtTkleMOfbaJPslOTnJx1rbzkluSHJLkvd3xjRprUle1869PMl5SX6xtX8nyZlJ/hE4uh3/4STXJ7mrjeeKJHcn+csx5/pckqVJ7khy6npcCknSehpKWLaA+jPg0KraBzi9fWp74GDgcOADYw55FfAOYE9gF+CgSfrdFLgUOL31exjwI+BtAFW1N3AccGGSzYBLgGPasdsDO1TV0nHd/jXwyaraH3hgCsN7Tq3tXBcAC1sNc4HfH3PMj6vq4Kq6pG0/XVWHAH8DfL7VvxdwcpJt2z6/U1X7AfOBt49pn1SSU5MsSbLkmScfm8JQJElTMayZ5aHAoqp6CKCqHm7tn6uqVVV1J/DiMfvfXFX3V9Uq4J+AeZP0uzuwsqpuaf3+sKqeYRDAF7W2FcB9wMuAy4Cj27HHAJdP0OdBwMXt9UVTGNtEte4O3FtV32r7XAgcMuaYS8f1sXoJeDlwR1WtrKqngHuAl7bPvT3JrcCNrW23XmFVdW5Vza+q+XM333IKQ5EkTcWw7lkGqAnanxq3z0TtzzJ5XZP1O+GybVV9L8m/JXklsBD4vUn6najPyUxU66TLxs0Tk/Sxalx/q4C5SRYwmDW/tqqeTHItsNla1ChJ2oCGNbP8GnDM6qXDJNtsoH5XADsk2b/1u2WSucD1wPGt7WXATsA32zGXAGcAW1XV8gn6XAwc214fvx51zUuya9s+AbhuHfsC2Ap4pAXlHsCB69GXJGk9DSUsq+oO4GzguraU+KEN1O/TDGaIH239fpXBjOsTwJwkyxkseZ7cljUBFjEIw8sm6fZ04G1JbmEQUutS14+BU4DLWw2rGNyPXFdfYjDDvA14P4OlWEnSiKRqbVYg9fPi+b+0c+1xwlmjLkOS1mjpOSeOuoSfkWRpVc0f3z4rfymBJElrY6P9pQRJrgR2Htf8rqr68jSce2+e+2TsU1X1mmGfW5K08dlow7KqjhzhuZcD+47q/JKkjYvLsJIkdRiWkiR1GJaSJHUYlpIkdRiWkiR1GJaSJHUYlpIkdRiWkiR1GJaSJHUYlpIkdRiWkiR1GJaSJHUYlpIkdRiWkiR1GJaSJHUYlpIkdRiWkiR1GJaSJHUYlpIkdRiWkiR1zB11ARqOl79kW5acc+Koy5CkGcGZpSRJHYalJEkdhqUkSR2GpSRJHYalJEkdhqUkSR2GpSRJHYalJEkdhqUkSR2GpSRJHYalJEkdhqUkSR2GpSRJHf6vIzPU0yvv4Lt/sfeoy5C0Ae105vJRlzBrObOUJKnDsJQkqcOwlCSpw7CUJKnDsJQkqcOwlCSpw7CUJKnDsJQkqcOwlCSpw7CUJKnDsJQkqcOwlCSpw7CUJKnDsJQkqcOwlCSpw7CUJKnDsJQkqcOwlCSpw7CUJKnDsJQkqcOwlCSpw7CUJKnDsJQkqcOwlCSpw7CUJKnDsJQkqWOjCsskWyf5g2k616eS7DlB+8lJPjYdNayLJAuSfGHUdUjSbLJWYZmBYQbs1sC0hGVVvaWq7pyOc62WZM50nk+StGF0gy/JvCR3JfkE8A3ghCQ3JPlGksuTbNH2+0CSO5PcluSvWtsFST6S5OtJ7kly1Jh+35nklrb/Wa35A8AvJ/mnJOesoaYzkixPcmuSD7S2fZPc2Pq7MskLkrw8yc3jxnJbe31tkvnt9SlJvpXkOuCgzvsx4ZjaPyTOSXJ7q21ha1+Q5Jok/wdY3mpY0Wa2tyf5TJLDkixOcneSA9pxB7RzLGsfd5/CtTo1yZIkSx5+4tne7pKkKZo7xf12B04BzgSuAA6rqieSvAv447ZseSSwR1VVkq3HHLs9cDCwB3AVsCjJrwO7AQcAAa5KcgjwbmCvqtp3skKSvB44AnhNVT2ZZJv2qU8Dp1XVdUn+AvjzqnpHkk2T7FJV9wALgcvG9bc9cBawH/AocA2wrPN+PGdMwG8C+wL7ANsBtyS5vu1/QBvXvUnmAbsCRwOnArcAb279vRF4TxvfCuCQqnomyWHAfwd+a01FVdW5wLkAr9zxedUZgyRpiqYalvdV1Y1JDgf2BBYnAdgUuAH4IfBj4FNJ/h4Ye0/tc1W1CrgzyYtb26+3P6tDaQsG4fndKdRyGHB+VT0JUFUPJ9kK2Lqqrmv7XAhc3l5fBhzDYNa6sP0Z6zXAtVX1IECSS4GXdWqYaEwHAxdX1bPA99ssdX8G783NVXXvmOPvrarl7Xx3AF9r/8hYDsxr+2wFXJhkN6CATXpvjCRpOKYalk+0jwG+WlXHjd+hLR++DjgW+EPg0Papp8buNubj/6iqvx3Xx7wp1BIG4TFVlwKXJ7kCqKq6e4J91nYWNtmYJvPEuO2xx68as72Kn16T9wPXVNWR7X25di1rlCRtIGv7sM6NwEFJdgVIsnmSl7X7lltV1ReBdzBYjlyTLwO/M+Z+545JXgQ8BmzZOfYr7djN27HbVNWjwCNJ/lPb5wTgOoCq+mfgWeC9DIJzvJuABUm2TbIJg+XRdXE9sDDJnCQvBA4Bbu4csyZbAd9rr09ej34kSetpqjNLAKrqwSQnAxcn+cXW/N8YhNznk2zGYIb1R51+vpLk5cANbTn3ceC3q+qf24MutwP/r6reOcGxX0qyL7AkydPAFxnc5zsJ+JsWovcwuMe62qXAOcDOE/S3Msn7GCwnr2TwENO6PLV6JfBa4FYGM9UzquqBJHusQ18A/5PBMuwfA1evYx+SpA0gVT4HMhO9csfn1Rd+b9dRlyFpA9rpzOWjLmHGS7K0quaPb9+ofimBJEkbo7Vahp1OSfYGLhrX/FRVvWaazv9nPPf+5eVVdfZ0nF+StPHYaMOy/WhF70GhYZ7/bMBglCS5DCtJUo9hKUlSh2EpSVKHYSlJUodhKUlSh2EpSVKHYSlJUodhKUlSh2EpSVKHYSlJUodhKUlSh2EpSVKHYSlJUodhKUlSh2EpSVKHYSlJUodhKUlSh2EpSVKHYSlJUsfcUReg4dh0+1ew05lLRl2GJM0IziwlSeowLCVJ6jAsJUnqMCwlSeowLCVJ6jAsJUnqMCwlSeowLCVJ6jAsJUnqMCwlSeowLCVJ6jAsJUnqMCwlSeowLCVJ6vC/6JqhVvxgBQd99KBRlyFJ02rxaYuH0q8zS0mSOgxLSZI6DEtJkjoMS0mSOgxLSZI6DEtJkjoMS0mSOgxLSZI6DEtJkjoMS0mSOgxLSZI6DEtJkjoMS0mSOgxLSZI6DEtJkjoMS0mSOgxLSZI6DEtJkjoMS0mSOgxLSZI6DEtJkjoMS0mSOgxLSZI6DEtJkjoMS0mSOmZtWCb5+iTtFyQ5arrrmaok70vyJ6OuQ5Jmk1kbllX1K9N9ziRzp/uckqT1N5Rv3kk+CNxXVZ9o2+8DHgN+GfhV4F4GQX1eVS1K8gbgQ8BDwDeAXarq8En63gL4KDAfKOCsqvpskuOA9wAB/r6q3pXk94Gdq+qMduzJwH5VdVqSx6tqiyRp/R3a6kpnbN8BLgT+C7AJcHRVrUiyDXAesAvwJHBqVd3Wxr4DMA94KMlXgCOAOcBewP8CNgVOAJ4C3lBVDyd5K3Bq+9y3gROq6sk1v/OSpGEY1szyEmDhmO1jgAcZBMbewFuA1wIk2Qz4W+D1VXUw8MJO3+8FHq2qvavqlcDVSXYAPsgg8PYF9k9yBLAI+M0xxy4ELh3X35HA7q2utwJTmXE+VFWvBj4JrF4SPQtY1mp6D/DpMfvvB7ypqt7ctvcC3gwcAJwNPFlVrwJuAE5s+1xRVftX1T7AXcDv9opKcmqSJUmW/OTxn0xhGJKkqRhKWFbVMuBFSXZIsg/wCPBq4PKqWlVVDwDXtN33AO6pqnvb9sWd7g8DPj7mXI8A+wPXVtWDVfUM8BngkKp6ELgnyYFJtmUQiovH9XcIcHFVPVtV/wpcPYUhXtE+LmXwDwCAg4GLWk1XA9sm2ap97qqq+tGY46+pqsdafY8C/7e1Lx/T315J/iHJcuB44BW9oqrq3KqaX1XzN9likykMQ5I0FcO8h7YIOAr4JQYzzV0n2W+Ny56T7F9r0celDGa2K4Arq2r8sUzQX89T7eOz/PQ9nKiG1f0+McnxAKvGbK8a098FwBFVdWtbPl6wljVKkjaQYT7gcwlwLIPAXAT8I/BbSX4hyYv56Tf/FcAuSea17YWs2VeAP1y9keQFwE3ArybZLskc4DjgurbLFQzuER7Hc5dgAa4Hjk0yJ8n2wK+txRjH93N8q2kBg6XaH65jXwBbAiuTbLK6X0nSaAxtZllVdyTZEvheVa1M8lngdcDtwLcYBNyjVfWjJH8AfCnJQ8DNna7/Evh4ktsZzOzOqqorkvwpg6XdAF+sqs+3Oh5JciewZ1VN1PeVDO51Lm91XTfBPlPxPuD8JLcxeMDnpHXsZ7X3MniP7mu1bbme/UmS1lEmXpUc0smSLarq8Xb/8GbgoKp6YEx7GNyPvLuqPjxthc1AW+y0Re3zzn1GXYYkTavFp41/LGXtJFlaVfPHt0/3z/19IcnWDH4c4v3tQR+AtyY5qbUvY/B0rCRJG4VpDcuqWjBJ+4eBn5lJJjkFOH3crour6m3Dqe5nJbkS2Hlc87uq6svTcX5J0sZjo/2NMlV1PnD+CM9/5KjOLUnauMzaX3cnSdJUGZaSJHUYlpIkdRiWkiR1GJaSJHUYlpIkdRiWkiR1GJaSJHUYlpIkdRiWkiR1GJaSJHUYlpIkdRiWkiR1GJaSJHUYlpIkdRiWkiR1GJaSJHUYlpIkdRiWkiR1GJaSJHXMHXUBGo49XrQHi09bPOoyJGlGcGYpSVKHYSlJUodhKUlSh2EpSVKHYSlJUodhKUlSR6pq1DVoCJI8Bnxz1HWM0HbAQ6MuYkRm89jB8Tv+9Rv/f6yqF45v9OcsZ65vVtX8URcxKkmWzNbxz+axg+N3/MMZv8uwkiR1GJaSJHUYljPXuaMuYMRm8/hn89jB8Tv+IfABH0mSOpxZSpLUYVhKktRhWM4wSX4jyTeTfDvJu0ddz7AleWmSa5LcleSOJKe39m2SfDXJ3e3jC0Zd6zAlmZNkWZIvtO2dk9zUxn9pkk1HXeOwJNk6yaIkK9rXwWtny/VP8kft6/72JBcn2WwmX/sk5yX5QZLbx7RNeK0z8JH2vfC2JK9en3MbljNIkjnAx4HXA3sCxyXZc7RVDd0zwH+tqpcDBwJva2N+N/C1qtoN+FrbnslOB+4as/1B4MNt/I8AvzuSqqbHXwNfqqo9gH0YvA8z/von2RF4OzC/qvYC5gDHMrOv/QXAb4xrm+xavx7Yrf05Ffjk+pzYsJxZDgC+XVX3VNXTwCXAm0Zc01BV1cqq+kZ7/RiDb5Q7Mhj3hW23C4EjRlPh8CV5CfCfgU+17QCHAovaLjN2/En+A3AI8HcAVfV0Vf07s+f6zwWel2QusDmwkhl87avqeuDhcc2TXes3AZ+ugRuBrZNsv67nNixnlh2BfxmzfX9rmxWSzANeBdwEvLiqVsIgUIEXja6yofvfwBnAqra9LfDvVfVM257JXwe7AA8C57dl6E8leT6z4PpX1feAvwK+yyAkHwWWMnuu/WqTXesN+v3QsJxZMkHbrPjZoCRbAJ8F3lFVPxx1PdMlyeHAD6pq6djmCXadqV8Hc4FXA5+sqlcBTzADl1wn0u7NvQnYGdgBeD6DpcfxZuq179mgfw8My5nlfuClY7ZfAvzriGqZNkk2YRCUn6mqK1rz91cvubSPPxhVfUN2EPDGJN9hsOx+KIOZ5tZtaQ5m9tfB/cD9VXVT217EIDxnw/U/DLi3qh6sqp8AVwC/wuy59qtNdq036PdDw3JmuQXYrT0NtymDm/1XjbimoWr35/4OuKuqPjTmU1cBJ7XXJwGfn+7apkNV/WlVvaSq5jG43ldX1fHANcBRbbeZPP4HgH9Jsntreh1wJ7Pj+n8XODDJ5u3vweqxz4prP8Zk1/oq4MT2VOyBwKOrl2vXhb/BZ4ZJ8gYGM4s5wHlVdfaISxqqJAcD/wAs56f37N7D4L7lZcBODL6pHF1V4x8MmFGSLAD+pKoOT7ILg5nmNsAy4Ler6qlR1jcsSfZl8HDTpsA9wCkMJgIz/vonOQtYyOCp8GXAWxjcl5uR1z7JxcACBv8N1/eBPwc+xwTXuv0D4mMMnp59Ejilqpas87kNS0mS1sxlWEmSOgxLSZI6DEtJkjoMS0mSOgxLSZI6DEtJkjoMS0mSOv4/8Kme9Ju3mZMAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "covid_normal_models = ['cnn_covid_normal', 'resnet_covid_normal', 'vgg_covid_normal']\n",
    "\n",
    "\n",
    "covid_normal_acc = [cnn_acc, res[1]*100, metric.result().numpy()*100]\n",
    "\n",
    "\n",
    "sns.barplot(x=covid_normal_acc, y=covid_normal_models)\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>false</th>\n",
       "      <th>true</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>false</th>\n",
       "      <td>47</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>true</th>\n",
       "      <td>0</td>\n",
       "      <td>50</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       false  true\n",
       "false     47     0\n",
       "true       0    50"
      ]
     },
     "execution_count": 31,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_cm_cn = pd.DataFrame(cm_cn, index=['false', 'true'], columns=['false', 'true'])\n",
    "df_cm_cn"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# COVID-19 VS NORMAL REPORT\n",
    "\n",
    "### CNN ACCURACY -> 93.81%\n",
    "### RESNET ACCURACY -> 77.32%\n",
    "### VGG ACCURACY -> 98.96%"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# COVID-19 VS PNEUMONIA"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_dataset(directory):\n",
    "    X, y = list(), list()\n",
    "    # enumerate folders, on per class\n",
    "    for subdir in ['Covid', 'PNEUMONIA']:\n",
    "        # path\n",
    "        path = directory + subdir + '/'\n",
    "        # skip any files that might be in the dir\n",
    "        if not isdir(path):\n",
    "            continue\n",
    "        # load all faces in the subdirectory\n",
    "        faces = load_images(path)\n",
    "        # create labels\n",
    "        labels = [subdir for _ in range(len(faces))]\n",
    "        # summarize progress\n",
    "        print('>loaded %d examples for class: %s' % (len(faces), subdir))\n",
    "        # store\n",
    "        X.extend(faces)\n",
    "        y.extend(labels)\n",
    "    return asarray(X), asarray(y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      ">loaded 94 examples for class: Covid\n",
      ">loaded 100 examples for class: PNEUMONIA\n"
     ]
    }
   ],
   "source": [
    "trainX, trainy = load_dataset('xray_dataset_covid19/')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "metadata": {},
   "outputs": [],
   "source": [
    "le = LabelEncoder()\n",
    "trainy = le.fit_transform(trainy)\n",
    "\n",
    "trainX, testX, trainy, testy = train_test_split(trainX, trainy, test_size=0.5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {},
   "outputs": [],
   "source": [
    "compute_loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)\n",
    "compute_accuracy = tf.keras.metrics.SparseCategoricalAccuracy()\n",
    "def test_cnn_covid_pneumonia(model, dataset):\n",
    "    \"\"\"\n",
    "    Perform an evaluation of `model` on the examples from `dataset`.\n",
    "    \"\"\"\n",
    "    avg_loss = metrics.Mean('loss', dtype=tf.float32)\n",
    "\n",
    "    for (images, labels) in dataset:\n",
    "        logits = model(images, training=False)\n",
    "        avg_loss(compute_loss(labels, logits))\n",
    "        compute_accuracy(labels, logits)\n",
    "\n",
    "    print('Model test set loss: {:0.4f} accuracy: {:0.2f}%'.format(\n",
    "        avg_loss.result(), compute_accuracy.result() * 100))\n",
    "\n",
    "    return(float(compute_accuracy.result() * 100))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {
    "collapsed": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16286ca90> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x16286ff90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x162873c90> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x162878210>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x16287c550> and <tensorflow.python.keras.layers.core.Dropout object at 0x16287e290>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16286ca90> and <tensorflow.python.keras.layers.core.Reshape object at 0x162864c90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x162873c90> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x16286ff90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Flatten object at 0x162878b90> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x162878210>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x16287c550> and <tensorflow.python.keras.layers.core.Flatten object at 0x162878b90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x16287eb90> and <tensorflow.python.keras.layers.core.Dropout object at 0x16287e290>).\n",
      "WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.\n"
     ]
    }
   ],
   "source": [
    "cnn_covid_pneumonia = keras.models.load_model('models/CNN_model_covid_pneumonia')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [],
   "source": [
    "resnet_covid_pneumonia = keras.models.load_model('models/ResNet_Model_Covid_Pneumonia')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {
    "collapsed": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e2f5350> and <tensorflow.python.keras.layers.core.Activation object at 0x16e2c4810>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16e2c5210> and <tensorflow.python.keras.layers.core.Dropout object at 0x16e2de650>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e2df150> and <tensorflow.python.keras.layers.core.Activation object at 0x16e2e1590>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16e2e1e10> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x16e2e5450>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e2ec250> and <tensorflow.python.keras.layers.core.Activation object at 0x16e2ef550>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16e2effd0> and <tensorflow.python.keras.layers.core.Dropout object at 0x16e2c9450>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e2c9fd0> and <tensorflow.python.keras.layers.core.Activation object at 0x16e2ce390>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16e2cec50> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x16e2fe250>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e2fefd0> and <tensorflow.python.keras.layers.core.Activation object at 0x16e3054d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16e305d90> and <tensorflow.python.keras.layers.core.Dropout object at 0x16e30d150>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e30dd10> and <tensorflow.python.keras.layers.core.Activation object at 0x16e317190>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16e317a50> and <tensorflow.python.keras.layers.core.Dropout object at 0x16e31ddd0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e3219d0> and <tensorflow.python.keras.layers.core.Activation object at 0x16e323e10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16e328710> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x16e32dd10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e332b10> and <tensorflow.python.keras.layers.core.Activation object at 0x16e336f90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16e337890> and <tensorflow.python.keras.layers.core.Dropout object at 0x16e33dbd0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e3427d0> and <tensorflow.python.keras.layers.core.Activation object at 0x16e345c50>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16eb08550> and <tensorflow.python.keras.layers.core.Dropout object at 0x16eb0d8d0>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16eb0c4d0> and <tensorflow.python.keras.layers.core.Activation object at 0x16eb17950>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16eb19250> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x16eb21850>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16eb23650> and <tensorflow.python.keras.layers.core.Activation object at 0x16eb27ad0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16eb2a3d0> and <tensorflow.python.keras.layers.core.Dropout object at 0x16eb30750>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16eb33350> and <tensorflow.python.keras.layers.core.Activation object at 0x16eb377d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16eb3c090> and <tensorflow.python.keras.layers.core.Dropout object at 0x16eb41410>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16eb41fd0> and <tensorflow.python.keras.layers.core.Activation object at 0x16d339490>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16d339d50> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x16d342390>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x16d346dd0> and <tensorflow.python.keras.layers.core.Activation object at 0x16d34ac90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16d34e590> and <tensorflow.python.keras.layers.core.Dropout object at 0x16d354850>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16e2c5210> and <tensorflow.python.keras.layers.core.Activation object at 0x16e2c4810>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e2df150> and <tensorflow.python.keras.layers.core.Dropout object at 0x16e2de650>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16e2e1e10> and <tensorflow.python.keras.layers.core.Activation object at 0x16e2e1590>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e2ec250> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x16e2e5450>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16e2effd0> and <tensorflow.python.keras.layers.core.Activation object at 0x16e2ef550>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e2c9fd0> and <tensorflow.python.keras.layers.core.Dropout object at 0x16e2c9450>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16e2cec50> and <tensorflow.python.keras.layers.core.Activation object at 0x16e2ce390>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e2fefd0> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x16e2fe250>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16e305d90> and <tensorflow.python.keras.layers.core.Activation object at 0x16e3054d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e30dd10> and <tensorflow.python.keras.layers.core.Dropout object at 0x16e30d150>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16e317a50> and <tensorflow.python.keras.layers.core.Activation object at 0x16e317190>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e3219d0> and <tensorflow.python.keras.layers.core.Dropout object at 0x16e31ddd0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16e328710> and <tensorflow.python.keras.layers.core.Activation object at 0x16e323e10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e332b10> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x16e32dd10>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16e337890> and <tensorflow.python.keras.layers.core.Activation object at 0x16e336f90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16e3427d0> and <tensorflow.python.keras.layers.core.Dropout object at 0x16e33dbd0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16eb08550> and <tensorflow.python.keras.layers.core.Activation object at 0x16e345c50>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16eb0c4d0> and <tensorflow.python.keras.layers.core.Dropout object at 0x16eb0d8d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16eb19250> and <tensorflow.python.keras.layers.core.Activation object at 0x16eb17950>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16eb23650> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x16eb21850>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16eb2a3d0> and <tensorflow.python.keras.layers.core.Activation object at 0x16eb27ad0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16eb33350> and <tensorflow.python.keras.layers.core.Dropout object at 0x16eb30750>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16eb3c090> and <tensorflow.python.keras.layers.core.Activation object at 0x16eb377d0>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.convolutional.Conv2D object at 0x16eb41fd0> and <tensorflow.python.keras.layers.core.Dropout object at 0x16eb41410>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16d339d50> and <tensorflow.python.keras.layers.core.Activation object at 0x16d339490>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dropout object at 0x16d342b90> and <tensorflow.python.keras.layers.pooling.MaxPooling2D object at 0x16d342390>).\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Flatten object at 0x16d346350> and <tensorflow.python.keras.layers.core.Dropout object at 0x16d342b90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x16d346dd0> and <tensorflow.python.keras.layers.core.Flatten object at 0x16d346350>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.normalization_v2.BatchNormalization object at 0x16d34e590> and <tensorflow.python.keras.layers.core.Activation object at 0x16d34ac90>).\n",
      "WARNING:tensorflow:Inconsistent references when loading the checkpoint into this object graph. Either the Trackable object references in the Python program have changed in an incompatible way, or the checkpoint was generated in an incompatible program.\n",
      "\n",
      "Two checkpoint references resolved to different objects (<tensorflow.python.keras.layers.core.Dense object at 0x16d3581d0> and <tensorflow.python.keras.layers.core.Dropout object at 0x16d354850>).\n",
      "WARNING:tensorflow:No training configuration found in save file, so the model was *not* compiled. Compile it manually.\n"
     ]
    }
   ],
   "source": [
    "vgg_covid_pneumonia = keras.models.load_model('models/VGG16_Model_Covid_Pneumonia')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model test set loss: 0.6927 accuracy: 51.55%\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "51.546390533447266"
      ]
     },
     "execution_count": 39,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "test_ds = tf.data.Dataset.from_tensor_slices((testX, testy)).batch(200)\n",
    "\n",
    "cnn_acc = test_cnn_covid_pneumonia(cnn_covid_pneumonia,test_ds)\n",
    "cnn_acc"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4/4 [==============================] - 12s 3s/step - loss: 0.0835 - accuracy: 0.9691\n"
     ]
    }
   ],
   "source": [
    "testy_ohe = tf.one_hot(testy, depth=3).numpy()\n",
    "res = resnet_covid_pneumonia.evaluate(testX, testy_ohe, verbose=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:5 out of the last 7 calls to <function recreate_function.<locals>.restored_function_body at 0x16fa849e0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please  define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.\n",
      "test acc: 0.9896907\n"
     ]
    }
   ],
   "source": [
    "db_test = tf.data.Dataset.from_tensor_slices((testX, testy)).batch(256)\n",
    "metric = keras.metrics.CategoricalAccuracy()\n",
    "for x, y in db_test:\n",
    "    # [b, 1] => [b]\n",
    "    # y = tf.squeeze(y, axis=1)\n",
    "    # [b, 10]\n",
    "    y = tf.one_hot(y, depth=3)\n",
    "\n",
    "    logits = vgg_covid_pneumonia.predict(x)\n",
    "    # be careful, these functions can accept y as [b] without warnning.\n",
    "    metric.update_state(y, logits)\n",
    "    cm_cp = confusion_matrix(tf.math.argmax(y, axis=1), tf.math.argmax(logits, axis=1))\n",
    "print('test acc:', metric.result().numpy())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAggAAAD4CAYAAACJ8R5TAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjEsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy8QZhcZAAAaKUlEQVR4nO3de5RlVXmu8eeVhiBgQFEJgqRRQYQgtwZREBHRxIR4V/QYBZJoLkQxibeYcxRMTDAmMVFQYoiAHg8iCIpolAQFFLl100pzaSQ2mEhQICIKKtfv/LFmDTc1q6uqgaoNXc9vjBq196y15vzm2ove755rVZGqQpIkadTDxl2AJEl68DEgSJKkjgFBkiR1DAiSJKljQJAkSZ1F4y5AeqA8+tGPrsWLF4+7DEl6SFm2bNlNVfWYye0GBK01Fi9ezNKlS8ddhiQ9pCT5zlTtXmKQJEkdA4IkSeoYECRJUseAIEmSOgYESZLUMSBIkqSOv+aotcaV3/0fdnvLx8ZdhnQvy9732nGXIN0nriBIkqSOAUGSJHUMCJIkqWNAkCRJHQOCJEnqGBAkSVLHgCBJkjoGBEmS1DEgSJKkjgFBkiR1DAiSJKljQJAkSR0DgiRJ6hgQJElSx4AgSZI6BgRJktQxIEiSpI4BQZIkdQwIkiSpY0CQJEkdA4IkSeoYECRJUseAIEmSOgYESZLUMSBIkqTOggwISV6Q5O2r+dmt813PfEny9XHXcF8kOTvJknHXIUkLyaJxFzAOVXU6cPq465hvVfWM+R4zyaKqumu+x5Uk3T9ztoKQ5LVJLk3yzSQfT3J8kg8k+XqSVUle1rbbt31CPCXJyiSfSJJp+t299fHNJBcleUSS9ZMcl2RFkuVJnt22vTDJDiP7np1ktyQHJzmqtW2d5PwkFyf5ixnmtG+Sc5OcluSKJMckeVj72a1J3tPquiDJZq39MUk+3fq/OMlerf3wJG8e6fuyJIvb18okx7a2TyTZP8l5Sa5Oskfb/lFJPtOO8QVJnjrS70fbXFcleePIGLe27xslOSvJJe2YvXCaOS9OcmWSf05yeZIzkzy8/WznNval7Zg8cuQ4/1WSc4DD2mv/4SRfaTU9q9V4ZZLjR8b6cJKlbZwjpnstJElza04CQntT/nNgv6raCTis/WhzYG/gAODIkV12Ad4EbA88AdhrNf2uB5wEHNb63R/4KXAoQFXtCLwKOCHJ+sAngVe0fTcHHldVyyZ1+4/Ah6tqd+B7s5jeHsCfAjsCTwRe0to3BC5odZ0LvG6k//e3/l8KHDuLMZ7U9nsqsB3wvxiO25uBd7RtjgCWV9VTW9vHRvbfDvjVVuu7kqw7qf+fAS+uql2BZwN/N10oA7YBjq6qHYAftnnQxnxbq2EF8K6RfTapqmdV1d+1548E9gP+GPgc8H5gB2DHJDu3bf68qpa0eT9rIvRMJ8nrW6hYetdPfjzT5pKkWZqrFYT9gFOq6iaAqvpBa/9MVd1TVVcAm41sf1FVfbeq7gG+ASxeTb9PBq6vqotbvz9qy9d7Ax9vbSuB7wDbAp8CXt72fQVw8hR97gWc2B5/fBZzu6iqVlXV3W2/vVv7HcAZ7fGykTnsDxyV5BsMlzV+MckjZhjjmqpa0Y7H5cBZVVUMb8IT/Y7O+cvApkk2bj/7fFXd3o7/Ddz7WAME+KsklwL/DmwxxTaT6/nG6NzaWJtU1Tmt/QRgn5F9TprUx+dG5vD9SfObmNMrklwCLGcID9tPUxNt7h+pqiVVtWTRBjMdVknSbM3VPQgBaor22ydtM1X73ay+rtX1O+Wn36q6Lsn/tE+iBwK/t5p+p+pzdSZvO/H8zvYGCPeew8OAp1fVT+9VcHIX9w5o6488Hj0e94w8v2ek36nmPDH+TMfz1cBjgN2q6s4k104af7LJ/T18mm0n3LaaPkbnM/F8UZKtGVZIdq+qm9ulh+lqkiTNoblaQTiL4dPgpjBcL3+A+l0JPC7J7q3fRyRZxLCk/+rWti2wFXBV2+eTwFuBjatqxRR9nge8sj1+9Sxq2KPdt/AwhtDxtRm2PxP4o4knI8vp1wK7trZdga1nMfao0TnvC9xUVT+a5b4bAze0cPBs4JfXcGyq6hbg5iTPbE2vAc6ZZpeZ/CJDqLil3b/x/PvRlyTpfpqTFYSqujzJe4BzktzNsGT8QPR7R5IDgQ+2G+V+yrCE/yHgmCQrgLuAg6tq4lPqKQzX81d3A+JhwP9Lchjw6VmUcT7D/RM7MrxJnzbD9m8Ejm7L+RNh5vfbWK9tlx4uBr41i7FHHQ4c1/r9CXDQGuz7CeBzSZYyXNJZuYZjTziI4bhvAKwCDrmP/VBV30yynOGSwyqG4CZJGpP8fFVcM2mf1N9cVQeMuxb1NvylrWu71/jLD3pwWfa+1467BGlaSZa1G8TvZUH+oSRJkjS9B+0fSkpyGv11+bdV1ZfmYewd6X+j4faqehpw9lyPPw7tfpGzpvjRc6rqf+a7HknSeD1oA0JVvXiMY68Adp5xw7VICwELas6SpNXzEoMkSeoYECRJUseAIEmSOgYESZLUMSBIkqSOAUGSJHUMCJIkqWNAkCRJHQOCJEnqGBAkSVLHgCBJkjoGBEmS1DEgSJKkjgFBkiR1DAiSJKljQJAkSR0DgiRJ6hgQJElSx4AgSZI6BgRJktRZNO4CpAfKU7bclKXve+24y5CktYIrCJIkqWNAkCRJHQOCJEnqGBAkSVLHgCBJkjoGBEmS1DEgSJKkjgFBkiR1DAiSJKljQJAkSR0DgiRJ6hgQJElSx4AgSZI6/t8ctda44/rL+c937zjuMiTpAbfVO1fM+5iuIEiSpI4BQZIkdQwIkiSpY0CQJEkdA4IkSeoYECRJUseAIEmSOgYESZLUMSBIkqSOAUGSJHUMCJIkqWNAkCRJHQOCJEnqGBAkSVLHgCBJkjoGBEmS1DEgSJKkjgFBkiR1DAiSJKljQJAkSR0DgiRJ6hgQJElSx4AgSZI6BgRJktQxIEiSpI4BQZIkdR5UASHJJkn+cJ7GOjbJ9lO0H5zkqPmoYb4leUGSt4+7jjWVZHGSy8ZdhyQtJGsUEDKYy1CxCTAvAaGqfreqrpiPsR4squr0qjpyPsech3NGkjQHZvyHu316uzLJh4BLgNckOT/JJUlOTrJR2+7IJFckuTTJ37a245N8IMnXk6xK8rKRft+S5OK2/RGt+UjgiUm+keR909T01iQrknwzyZGtbeckF7T+TkvyyCRPSXLRpLlc2h6fnWRJe3xIkm8lOQfYa4bjcXySY5J8te1zQGs/OMmpSb6Y5OokfzOyz/NWc8yuTfLo9nhJkrPb48OTnJDkzLbNS5L8TZvzF5Os27Z7TpLlrf2jSX5hpN8j2ngrkmw3UuNR7fFvJrmw7f/vSTabZs6Ht/7Pbq/jG0d+9idJLmtfbxo5zqPnzOOT3JrkvUmWtfH2GOnvBSP7fbXVfUmSZ0z3WrR9Xp9kaZKlP7jt7pk2lyTN0mw/2T0Z+BjwXOB3gP2raldgKfAnSR4FvBjYoaqeCvzlyL6bA3sDBzAEAJI8D9gG2APYGdgtyT7A24FvV9XOVfWWqQpJ8nzgRcDTqmonYOKN+GPA29r4K4B3VdWVwHpJntC2ORD41KT+NgeOYAgGzwW6yw5TWAw8C/gN4Jgk67f2ndsYOwIHJnl8CwD/e/Ixm8UYT2z9vxD4v8BXqmpH4KfAb7QxjwcObO2LgD8Y2f+mNt6HgTdP0f/XgD2rahfgk8BbZ6hnO+BXGV6zdyVZN8luwCHA04A9gdcl2aVt/2TgY1W1S1V9B9gQOLuqdgN+zHCOPJfhvHl32+cG4Lmt7gOBD8xQE1X1kapaUlVLHrXhOjNtLkmapUWz3O47VXVB+7S8PXBeEoD1gPOBHwE/A45N8nngjJF9P1NV9wBXjHxKfV77Wt6eb8QQGP5zFrXsDxxXVT8BqKofJNkY2KSqzmnbnACc3B5/CngFQzg5sH2NehrDG9eNAElOAradoYZPtTldnWQVw5snwFlVdUvr5wrglxkum0x1zGbyr1V1Z5IVwDrAF1v7CoaA8mTgmqr61sicDwX+oT0/tX1fBrxkiv63BE5qAWk94JoZ6vl8Vd0O3J7kBmAzhuB3WlXd1uZ8KvBM4HTaOTOy/x2T5nD7yPwWt/Z1gaOS7AzczcyvgyRpjsw2INzWvgf4t6p61eQNkuwBPAd4JfBHwH7tR7ePbjby/a+r6p8m9bF4FrUEqFnWDXAScHJ786qqunqKbdakv6m2n3g+Ote7GY7vao8ZcBc/X8VZf9LPbgeoqnuS3FlVE2PcM9LvdCZqmahjsg8Cf19VpyfZFzh8lv2N9jldDbdNej55DqPzm6jvj4HvAzsxHJefzVCTJGmOrOnNYxcAeyV5EkCSDZJs266pb1xVXwDexLDUPp0vAb89ci1+iySPZVh6fsQM+57Z9t2g7fuo9qn95iTPbNu8BjgHoKq+zfCG9n8YwsJkFwL7Jtm0Xdt/+QzjA7w8ycOSPBF4AnDVNNtOeczaz64FdmuPXzqLcUetBBZP9MvInGdpY+C69vigNRx7wrnAi9qcNmS4XPDV+9jXRE3Xt9WZ1zCsnEiSxmC2KwgAVNWNSQ4GTpy4IY7h+vqPgc+26+Jh+CQ4XT9nJnkKcH5bdr8V+K2q+naS8zL8Stu/TnUfQlV9sS1BL01yB/AF4B0Mb3LHtOCwiuHa+ISTgPcBW0/R3/VJDmdY9r+e4aa6md6YrmJ4M94M+P2q+lmbx1RzXd0x+xbDvQ//kuQdDEFl1tqYhzCsjiwCLgaOWYMuDm/7XscQYrpjM4saLklyPDBxI+ixVbV8litBU/kQ8OkkLwe+Qr8KIUmaJ/n5qq9mo70hnlFVp4y7Ft3bU7d4eJ3xe0+aeUNJeojZ6p0r5qzvJMuqasnkdn8/XZIkddboEsN8SrIj8PFJzbdX1dPmafw/p78f4eSqOng+xh+HdsnisEnN51XVoeOoR5I0Pg/agFBVK5j5Zse5HP89wHvGNf44VNVxwHHjrkOSNH5eYpAkSR0DgiRJ6hgQJElSx4AgSZI6BgRJktQxIEiSpI4BQZIkdQwIkiSpY0CQJEkdA4IkSeoYECRJUseAIEmSOgYESZLUMSBIkqSOAUGSJHUMCJIkqWNAkCRJHQOCJEnqGBAkSVJn0bgLkB4o622+A1u9c+m4y5CktYIrCJIkqWNAkCRJHQOCJEnqGBAkSVLHgCBJkjoGBEmS1DEgSJKkjgFBkiR1DAiSJKljQJAkSR0DgiRJ6hgQJElSx4AgSZI6BgRJktTxf/estcbKG1ay1wf3GncZkjSvznvDeXPSrysIkiSpY0CQJEkdA4IkSeoYECRJUseAIEmSOgYESZLUMSBIkqSOAUGSJHUMCJIkqWNAkCRJHQOCJEnqGBAkSVLHgCBJkjoGBEmS1DEgSJKkjgFBkiR1DAiSJKljQJAkSR0DgiRJ6hgQJElSx4AgSZI6BgRJktQxIEiSpI4BQZIkdQwIkiSps2ADQpKvr6b9+CQvm+965kOSdyfZf9x1rKkkByc5atx1SNJCsmjcBYxLVT1j3DXMt6p653yPmWRRVd013+NKku6fOVlBSPLeJH848vzwJH+a5ENJLk9yRpIvTHxST/LrSVYm+VqSDyQ5Y5q+N0pyXJIVSS5N8tLW/qrWdlmS97a2P0jyNyP7Hpzkg+3xre17khyV5IoknwceO8Pcrm3zu6h9Pam1H99q/3qSVaOrEEnekuTiVu8RrW1xkstGtnlzksPb47OTvD/JuUmuTLJ7klOTXJ3kL0f2+ZM238uSvGmk3yuT/HM71mcmefhIjRPH/J2tpsuSfCRJppnz2SNz/laSZ7b29Udei+VJnj1ynE9O8jngzCT7Jjknyafa/kcmeXXrb0WSJ7b9fjPJha2vf0+y2XSvhSRp7szVJYZPAgeOPH8FcCOwGNgR+F3g6TC8yQD/BDy/qvYGHjND3/8HuKWqdqyqpwJfTvI44L3AfsDOwO5JXgScArxkZN8DgZMm9fdi4MmtrtcBs1lZ+FFV7QEcBfzDSPvmwN7AAcCRbX7PA7YB9mi17ZZkn1mMcUdV7QMcA3wWOBT4FeDgJJsm2Q04BHgasCfwuiS7tH23AY6uqh2AHwIvnaL/o6pq96r6FeDhrebpLGpzfhPwrtZ2KEBV7Qi8CjihvZ4wvL4HVdV+7flOwGEMx/k1wLatv2OBN7RtvgbsWVW7MJxDb52hJpK8PsnSJEvvvPXOmTaXJM3SnASEqloOPDbJ45LsBNwM7AqcXFX3VNX3gK+0zbcDVlXVNe35iTN0vz9w9MhYNwO7A2dX1Y1tOfsTwD5VdSOwKsmeSTZlCALnTepvH+DEqrq7qv4b+PIspnjiyPenj7R/ps3vCmDi0+/z2tdy4JI2321mMcbp7fsK4PKqur6qbgdWAY9nCCKnVdVtVXUrcCrwzLbPNVX1jfZ4GUMwm+zZ7dP6CoZgtcMM9Zw6RX97Ax8HqKqVwHeAbdvP/q2qfjCy/8Ujc/g2cObI/Cb62xL4UqvpLbOoiar6SFUtqaol62607kybS5JmaS7vQTgFeBnwSwyfBp+0mu1Wu7Q9zfa1Bn2cxLCCsZLhDXXyvkzR30xqNY9vn6KmAH9dVf802kGSLbl3QFufe5vo655J/d7D8LpNN+fR7e9mWCEYHXt94EPAkqr6r3ZpY/L4q+vzbn5+3kxXw23T1DQ6p4n5AHwQ+PuqOj3JvsDhM9QkSZojc/lbDJ8EXskQEk5hWD5+aZKHtWvL+7btVgJPSLK4PT+Q6Z0J/NHEkySPBC4EnpXk0UnWYVjuPqdtcirwotY2+fICwLnAK5Osk2Rz4NmzmNuBI9/Pn2HbLwG/nWSjVu8WSR4LfJ9hlWXTJL/AzEv8U9X9oiQbJNmQ4VLJV2e570QYuKnVdV9/a+Nc4NUASbYFtgKuuo99AWwMXNceH3Q/+pEk3U9ztoJQVZcneQRwXVVdn+TTwHOAy4BvMbyp31JVP81wQ+MXk9wEXDRD138JHN1u8LsbOKKqTk3yZwyXLQJ8oao+2+q4OckVwPZVNVXfpzEssa9odZ0zxTaT/UKSCxkC1qtmOA5nJnkKcH67D/BW4Leq6oYk727H4RqGoDRrVXVJkuP5+fE6tqqWjwSt6fb9YZJ/ZpjztcDFazL2iA8Bx7RLAncBB1fV7dPc7ziTw4GTk1wHXABsfV87kiTdP5l6xX2OBks2qqpb2/0AFwF7VdX3RtrDcH/B1VX1/nkrbA0kuZZhaf6mcdeie9toq41qp7fsNO4yJGlenfeGybfWrZkky6pqyeT2+f47CGck2QRYD/iLdrMiDHfgH9TalzP8VoMkSRqTeQ0IVbXvatrfD9xrxSDJIQy/FjfqvKo6dG6qu7ckp9Evcb+tqhbPx/jjkORoYK9Jzf9YVceNox5J0vg8aP+SYntTGtsbU1W9eFxjj8t8hS9J0oPfgv1/MUiSpNUzIEiSpI4BQZIkdQwIkiSpY0CQJEkdA4IkSeoYECRJUseAIEmSOgYESZLUMSBIkqSOAUGSJHUMCJIkqWNAkCRJHQOCJEnqGBAkSVLHgCBJkjoGBEmS1DEgSJKkjgFBkiR1DAiSJKmzaNwFSA+U7R67Hee94bxxlyFJawVXECRJUseAIEmSOgYESZLUMSBIkqSOAUGSJHUMCJIkqZOqGncN0gMiyY+Bq8Zdxxg9Grhp3EWM2UI/Bgt9/uAxuC/z/+WqeszkRv8OgtYmV1XVknEXMS5Jli7k+YPHYKHPHzwGD+T8vcQgSZI6BgRJktQxIGht8pFxFzBmC33+4DFY6PMHj8EDNn9vUpQkSR1XECRJUseAIEmSOgYEPeQl+bUkVyX5jyRvH3c98yHJ45N8JcmVSS5Pclhrf1SSf0tydfv+yHHXOpeSrJNkeZIz2vOtk1zY5n9SkvXGXeNcSrJJklOSrGznwtMX0jmQ5I/b+X9ZkhOTrL+2nwNJPprkhiSXjbRN+Zpn8IH2b+OlSXZdk7EMCHpIS7IOcDTwfGB74FVJth9vVfPiLuBPq+opwJ7AoW3ebwfOqqptgLPa87XZYcCVI8/fC7y/zf9m4HfGUtX8+Ufgi1W1HbATw7FYEOdAki2ANwJLqupXgHWAV7L2nwPHA782qW11r/nzgW3a1+uBD6/JQAYEPdTtAfxHVa2qqjuATwIvHHNNc66qrq+qS9rjHzO8MWzBMPcT2mYnAC8aT4VzL8mWwG8Ax7bnAfYDTmmbrO3z/0VgH+BfAKrqjqr6IQvoHGD4Y38PT7II2AC4nrX8HKiqc4EfTGpe3Wv+QuBjNbgA2CTJ5rMdy4Cgh7otgP8aef7d1rZgJFkM7AJcCGxWVdfDECKAx46vsjn3D8BbgXva802BH1bVXe352n4uPAG4ETiuXWY5NsmGLJBzoKquA/4W+E+GYHALsIyFdQ5MWN1rfr/+fTQg6KEuU7QtmN/dTbIR8GngTVX1o3HXM1+SHADcUFXLRpun2HRtPhcWAbsCH66qXYDbWEsvJ0ylXWd/IbA18DhgQ4Yl9cnW5nNgJvfrvwkDgh7qvgs8fuT5lsB/j6mWeZVkXYZw8ImqOrU1f39iCbF9v2Fc9c2xvYAXJLmW4bLSfgwrCpu05WZY+8+F7wLfraoL2/NTGALDQjkH9geuqaobq+pO4FTgGSysc2DC6l7z+/XvowFBD3UXA9u0O5fXY7hJ6fQx1zTn2vX2fwGurKq/H/nR6cBB7fFBwGfnu7b5UFV/VlVbVtVihtf8y1X1auArwMvaZmvt/AGq6nvAfyV5cmt6DnAFC+QcYLi0sGeSDdp/DxPzXzDnwIjVveanA69tv82wJ3DLxKWI2fAvKeohL8mvM3x6XAf4aFW9Z8wlzbkkewNfBVbw82vw72C4D+FTwFYM/4C+vKom39C0VkmyL/DmqjogyRMYVhQeBSwHfquqbh9nfXMpyc4MN2muB6wCDmH44LcgzoEkRwAHMvxWz3Lgdxmusa+150CSE4F9Gf63zt8H3gV8hile8xacjmL4rYefAIdU1dJZj2VAkCRJk3mJQZIkdQwIkiSpY0CQJEkdA4IkSeoYECRJUseAIEmSOgYESZLU+f+TUYl+VXnJhgAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "covid_pneumonia_models = ['cnn_covid_pneumonia_normal', 'resnet_covid_pneumonia_normal', 'vgg_covid_pneumonia_normal']\n",
    "\n",
    "\n",
    "covid_pneumonia_acc = [cnn_acc, res[1]*100, metric.result().numpy()*100]\n",
    "splot = sns.barplot(x=covid_pneumonia_acc, y=covid_pneumonia_models)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_cm_cp = pd.DataFrame(cm_cp, index=['false', 'true'], columns=['false', 'true'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>false</th>\n",
       "      <th>true</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>false</th>\n",
       "      <td>46</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>true</th>\n",
       "      <td>0</td>\n",
       "      <td>50</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       false  true\n",
       "false     46     1\n",
       "true       0    50"
      ]
     },
     "execution_count": 44,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_cm_cp"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# COVID-19 VS PNEUMONIA REPORT\n",
    "\n",
    "### CNN ACCURACY -> 51.51%\n",
    "### RESNET ACCURACY -> 96.91%\n",
    "### VGG ACCURACY -> 98.96%"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
